export enum EventNames {
  ItemsChanged = 'items:changed',
  ProductSelect = 'product:select',
  ModalOpen = 'modal:open',
  ModalClose = 'modal:close',
  BasketChanged = 'basket:changed',
  BasketAdd = 'basket:add',
  BasketItemAdded = 'basket:itemAdded',
  BasketItemRemoved = 'basket:itemRemoved',
  BidsOpen = 'bids:open',
  BasketRemove = 'basket:remove',
  OrderOpen = 'order:open',
  FormErrorsChange = 'formErrors:change',
  OrderAddressChange = 'order.address:change',
  OrderPaymentChange = 'order.payment:change',
  OrderSubmit = 'order:submit',
  ContactsPhoneChange = 'contacts.phone:change',
  ContactsEmailChange = 'contacts.email:change',
  ContactsSubmit = 'contacts:submit',
  OrderChanged = 'order:changed',
};